; Configuration Information File

[database]
host = localhost
name = elitalerts
port = 3306
user = elitalerts
pass = 45xr61ElitAlerts

[credentials]
user = elitalerts
pass = 45xr61ElitAlerts

[apn-dev]
url = "ssl://gateway.sandbox.push.apple.com:2195"
passphrase = elitalerts
cert = "eLitAlertsDev.pem"

[apn-prod]
url = "ssl://gateway.push.apple.com:2195"
passphrase = key4ELitAlerts
cert = "aps_production_elitalerts_ck.pem"

[debug]
enabled = true

[env]
production = true